nwip: unit test crashes with:
 FAIL   webkit  src/use-query.test.tsx > useQuery when ZeroProvider is used, view is reused if query instance changes as long as hash does not change
TypeError: zero.materialize is not a function. (In 'zero.materialize(query, createSolidViewFactory(setState), { ttl })', 'zero.materialize' is undefined)
 ❯ src/use-query.ts:93:32
     91|           prevView.destroy();
     92|         }
     93|         view = zero.materialize(query, createSolidViewFactory(setState), {ttl});